name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  galaxeus_lib: ^0.0.64
  http: ^0.13.6
  isar: ^3.1.0+1
  isar_inspector: 
   path: ../

dev_dependencies:
  build_runner: ^2.4.4
  isar_generator: ^3.1.0+1
  lints: ^2.0.0
  test: ^1.21.0
