name: isar_inspector
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 3.1.0+3
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev

funding:
  - https://github.com/sponsors/leisim/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  font_awesome_flutter: any

  isar: ^3.1.0+1

  go_router: ^5.0.0
  google_fonts: ^4.0.4
  vm_service: ^9.0.0
  web_socket_channel: ^2.2.0
  universal_io: ^2.2.0
  path: ^1.8.3
  http: ^0.13.6

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
